### ISSUE TITLE
CSS 三角形

### ISSUE THREAD

**Issue by zjffun** [zjffun/note#16]
```css
.triangle {
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 0 6px 8px 6px;
  border-color: transparent transparent aqua transparent;
}
```
