### ISSUE TITLE
自定义 file input

### ISSUE THREAD

**Issue by zjffun** [zjffun/note#22]
# 使用 `label`

```html
<label class="btn btn-default btn-file">
    Browse <input type="file" style="display: none;">
</label>
```

# 使用透明度

```html
<div class="upload-btn-wrapper">
  <button class="btn">Upload a file</button>
  <input type="file" name="myfile" />
</div>
```

```css
.upload-btn-wrapper {
  position: relative;
  overflow: hidden;
  display: inline-block;
}

.btn {
  border: 2px solid gray;
  color: gray;
  background-color: white;
  padding: 8px 20px;
  border-radius: 8px;
  font-size: 20px;
  font-weight: bold;
}

.upload-btn-wrapper input[type=file] {
  font-size: 100px;
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
}
```
# 参见
- [Custom File Upload Button With Pure CSS - Bene Studio](https://blog.benestudio.co/custom-file-upload-button-with-pure-css-5aacf39aa0a)
- [html - How to customize <input type="file">? - Stack Overflow](https://stackoverflow.com/questions/5813344/how-to-customize-input-type-file)
